// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HttpCaptureDiffContract {
    "schema_version": number;
    "source_result_type": string;
    "result_type": string;
    "url_template_version": number;
    "supported_source_versions": number[];
    "default_template_limit": number;
    "max_template_limit": number;
    "default_table_limit": number;
    "max_table_limit": number;
    "time_alignment_grades": string[];
    "workspace_route": string;
    "workspace_selection_count": number;
    "compare_method": string;
    "legacy_diff_supported": boolean;
    "requires_new_nav_key": boolean;
    "store_rescan_on_diff_or_export": boolean;
    "process_requires_real_sources": boolean;

    /** Creates a new HttpCaptureDiffContract instance. */
    constructor($$source: Partial<HttpCaptureDiffContract> = {}) {
        if (!("schema_version" in $$source)) {
            this["schema_version"] = 0;
        }
        if (!("source_result_type" in $$source)) {
            this["source_result_type"] = "";
        }
        if (!("result_type" in $$source)) {
            this["result_type"] = "";
        }
        if (!("url_template_version" in $$source)) {
            this["url_template_version"] = 0;
        }
        if (!("supported_source_versions" in $$source)) {
            this["supported_source_versions"] = [];
        }
        if (!("default_template_limit" in $$source)) {
            this["default_template_limit"] = 0;
        }
        if (!("max_template_limit" in $$source)) {
            this["max_template_limit"] = 0;
        }
        if (!("default_table_limit" in $$source)) {
            this["default_table_limit"] = 0;
        }
        if (!("max_table_limit" in $$source)) {
            this["max_table_limit"] = 0;
        }
        if (!("time_alignment_grades" in $$source)) {
            this["time_alignment_grades"] = [];
        }
        if (!("workspace_route" in $$source)) {
            this["workspace_route"] = "";
        }
        if (!("workspace_selection_count" in $$source)) {
            this["workspace_selection_count"] = 0;
        }
        if (!("compare_method" in $$source)) {
            this["compare_method"] = "";
        }
        if (!("legacy_diff_supported" in $$source)) {
            this["legacy_diff_supported"] = false;
        }
        if (!("requires_new_nav_key" in $$source)) {
            this["requires_new_nav_key"] = false;
        }
        if (!("store_rescan_on_diff_or_export" in $$source)) {
            this["store_rescan_on_diff_or_export"] = false;
        }
        if (!("process_requires_real_sources" in $$source)) {
            this["process_requires_real_sources"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpCaptureDiffContract instance from a string or object.
     */
    static createFrom($$source: any = {}): HttpCaptureDiffContract {
        const $$createField4_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported_source_versions" in $$parsedSource) {
            $$parsedSource["supported_source_versions"] = $$createField4_0($$parsedSource["supported_source_versions"]);
        }
        if ("time_alignment_grades" in $$parsedSource) {
            $$parsedSource["time_alignment_grades"] = $$createField9_0($$parsedSource["time_alignment_grades"]);
        }
        return new HttpCaptureDiffContract($$parsedSource as Partial<HttpCaptureDiffContract>);
    }
}

export class WorkspaceComparisonRoute {
    "supported": boolean;
    "route"?: string;
    "method"?: string;
    "result_type"?: string;
    "reason"?: string;

    /** Creates a new WorkspaceComparisonRoute instance. */
    constructor($$source: Partial<WorkspaceComparisonRoute> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceComparisonRoute instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceComparisonRoute {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceComparisonRoute($$parsedSource as Partial<WorkspaceComparisonRoute>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
