// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../../internal/capture/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as aggregate$0 from "../../internal/capture/aggregate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as certstore$0 from "../../internal/capture/certstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../internal/capture/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeCaptureSession(request: $models.CaptureAnalyzeRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(315565375, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FetchCaptureTransactions(request: $models.CaptureFetchRequest): $CancellablePromise<store$0.Page> {
    return $Call.ByID(1653085832, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCaptureCAStatus(): $CancellablePromise<certstore$0.Status> {
    return $Call.ByID(895633267).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetCaptureSnapshot(sessionID: string): $CancellablePromise<aggregate$0.Snapshot> {
    return $Call.ByID(1555410437, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCaptureStats(sessionID: string): $CancellablePromise<capture$0.Stats> {
    return $Call.ByID(2953265700, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ImportHar(request: $models.CaptureImportRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(1038261337, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InstallCaptureCA(): $CancellablePromise<certstore$0.Status> {
    return $Call.ByID(1385602692).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListCaptureModes(): $CancellablePromise<capture$0.Mode[]> {
    return $Call.ByID(1386420617).then(($result: any) => {
        return $$createType6($result);
    });
}

export function RecoverCaptureSessions(): $CancellablePromise<store$0.RecoveryReport[]> {
    return $Call.ByID(740397896).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RemoveCaptureCA(): $CancellablePromise<certstore$0.Status> {
    return $Call.ByID(365362915).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartCapture(config: capture$0.Config): $CancellablePromise<capture$0.Session> {
    return $Call.ByID(2002208921, config).then(($result: any) => {
        return $$createType9($result);
    });
}

export function StopCapture(sessionID: string): $CancellablePromise<capture$0.Session> {
    return $Call.ByID(328652407, sessionID).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.AnalysisResult.createFrom;
const $$createType1 = store$0.Page.createFrom;
const $$createType2 = certstore$0.Status.createFrom;
const $$createType3 = aggregate$0.Snapshot.createFrom;
const $$createType4 = capture$0.Stats.createFrom;
const $$createType5 = capture$0.Mode.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = store$0.RecoveryReport.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = capture$0.Session.createFrom;
