// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiler$0 from "../../internal/profiler/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * [한글] Analyze — 동기 분석. 호출 즉시 결과 반환. 결과가 작은 경우 또는
 * 호출자가 progress 가 필요 없는 경우에 사용. 큰 입력은 AnalyzeAsync 추천.
 */
export function Analyze(req: $models.AnalyzeRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(2962401776, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeAsync starts a non-blocking analysis. Returns a taskId immediately;
 * the renderer listens for `analyze:done` / `analyze:error` /
 * `analyze:cancelled` events keyed by that taskId. The progress log is
 * opened synchronously so its path is present in the response, giving
 * the renderer something to show even if the OS kills the process
 * before the result event arrives.
 */
export function AnalyzeAsync(req: $models.AnalyzeRequest): $CancellablePromise<$models.AnalyzeAsyncResponse> {
    return $Call.ByID(1198804148, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Cancel signals a previously started AnalyzeAsync to discard its result.
 * Returns true if the task existed; false if it had already finished.
 */
export function Cancel(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2907751950, taskID);
}

/**
 * [한글] Diff — baseline/target 두 파일을 비교 분석.
 * 형식별 parser → stack map 통일 → AnalyzeProfilerDiff 호출.
 * Normalize=true 면 양쪽을 자기 합계로 정규화(권장 default).
 */
export function Diff(req: $models.DiffRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(3785065275, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * [한글] Drilldown — 분석 + drilldown 필터 시퀀스 적용. 결과 stages 반환.
 * 보통 분석은 한 번 캐시해두는 게 효율적이지만, 단순화를 위해 매 호출마다 재분석.
 */
export function Drilldown(req: $models.DrilldownRequest): $CancellablePromise<profiler$0.DrilldownStage[]> {
    return $Call.ByID(1083076133, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * [한글] ExportPprof — collapsed map 을 pprof.gz 로 export.
 * outputPath 비어있으면 SaveFile dialog 로 사용자에게 묻고, 취소 시 에러.
 * intervalMs<=0 면 100ms 디폴트.
 */
export function ExportPprof(req: $models.ExportPprofRequest): $CancellablePromise<$models.ExportPprofResponse> {
    return $Call.ByID(3897807737, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PickPprofOutput(): $CancellablePromise<string> {
    return $Call.ByID(667369069);
}

export function PickProfileFile(): $CancellablePromise<string> {
    return $Call.ByID(3229459112);
}

/**
 * WriteDebugLog runs an analysis with the debug log enabled and returns the
 * saved JSON path. Renderer uses this from the Diagnostics tab.
 * 
 * [한글] WriteDebugLog — debug log 강제 ON 으로 분석 실행 후 JSON 파일 기록.
 * 분석 자체가 실패해도 exception 을 debug log 에 추가 후 (가능하면) 기록.
 * 진단할 내용이 없으면 outputPath 비운 채 verdict 만 반환.
 */
export function WriteDebugLog(req: $models.AnalyzeRequest): $CancellablePromise<$models.DebugLogResult> {
    return $Call.ByID(45456632, req).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = profiler$0.AnalysisResult.createFrom;
const $$createType1 = $models.AnalyzeAsyncResponse.createFrom;
const $$createType2 = profiler$0.DrilldownStage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ExportPprofResponse.createFrom;
const $$createType5 = $models.DebugLogResult.createFrom;
