// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Contract {
    "schema_version": number;
    "result_type": string;
    "http_result_type": string;
    "optional_result_types": string[];
    "alignment_grades": string[];
    "confidence_grades": string[];
    "default_top_n": number;
    "max_top_n": number;
    "default_time_tolerance_ms": number;
    "max_time_tolerance_ms": number;
    "analyze_method": string;
    "requires_profile_wall_clock_anchor": boolean;
    "store_or_file_rescan": boolean;
    "causal_claims_allowed": boolean;

    /** Creates a new Contract instance. */
    constructor($$source: Partial<Contract> = {}) {
        if (!("schema_version" in $$source)) {
            this["schema_version"] = 0;
        }
        if (!("result_type" in $$source)) {
            this["result_type"] = "";
        }
        if (!("http_result_type" in $$source)) {
            this["http_result_type"] = "";
        }
        if (!("optional_result_types" in $$source)) {
            this["optional_result_types"] = [];
        }
        if (!("alignment_grades" in $$source)) {
            this["alignment_grades"] = [];
        }
        if (!("confidence_grades" in $$source)) {
            this["confidence_grades"] = [];
        }
        if (!("default_top_n" in $$source)) {
            this["default_top_n"] = 0;
        }
        if (!("max_top_n" in $$source)) {
            this["max_top_n"] = 0;
        }
        if (!("default_time_tolerance_ms" in $$source)) {
            this["default_time_tolerance_ms"] = 0;
        }
        if (!("max_time_tolerance_ms" in $$source)) {
            this["max_time_tolerance_ms"] = 0;
        }
        if (!("analyze_method" in $$source)) {
            this["analyze_method"] = "";
        }
        if (!("requires_profile_wall_clock_anchor" in $$source)) {
            this["requires_profile_wall_clock_anchor"] = false;
        }
        if (!("store_or_file_rescan" in $$source)) {
            this["store_or_file_rescan"] = false;
        }
        if (!("causal_claims_allowed" in $$source)) {
            this["causal_claims_allowed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contract instance from a string or object.
     */
    static createFrom($$source: any = {}): Contract {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("optional_result_types" in $$parsedSource) {
            $$parsedSource["optional_result_types"] = $$createField3_0($$parsedSource["optional_result_types"]);
        }
        if ("alignment_grades" in $$parsedSource) {
            $$parsedSource["alignment_grades"] = $$createField4_0($$parsedSource["alignment_grades"]);
        }
        if ("confidence_grades" in $$parsedSource) {
            $$parsedSource["confidence_grades"] = $$createField5_0($$parsedSource["confidence_grades"]);
        }
        return new Contract($$parsedSource as Partial<Contract>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
