// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AnalysisResult is the universal envelope. Each analyzer populates
 * only the fields it needs; the rest stay as their zero value.
 * 
 * `Series` / `Tables` / `Charts` / `Summary` are kept as
 * `map[string]any` rather than typed structs because the Python
 * implementation projects different shapes per analyzer (access log
 * = per-minute timeline; profiler = flame tree; thread dump = state
 * distribution). The renderer uses the `Type` field to decide which
 * keys to look for; the parity job just diffs the JSON.
 */
export class AnalysisResult {
    "type": string;
    "source_files": string[];
    "created_at": string;
    "summary": { [_ in string]?: any };
    "series": { [_ in string]?: any };
    "tables": { [_ in string]?: any };
    "charts": { [_ in string]?: any };
    "metadata": Metadata;

    /** Creates a new AnalysisResult instance. */
    constructor($$source: Partial<AnalysisResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source_files" in $$source)) {
            this["source_files"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = {};
        }
        if (!("series" in $$source)) {
            this["series"] = {};
        }
        if (!("tables" in $$source)) {
            this["tables"] = {};
        }
        if (!("charts" in $$source)) {
            this["charts"] = {};
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalysisResult {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_files" in $$parsedSource) {
            $$parsedSource["source_files"] = $$createField1_0($$parsedSource["source_files"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField4_0($$parsedSource["series"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("charts" in $$parsedSource) {
            $$parsedSource["charts"] = $$createField6_0($$parsedSource["charts"]);
        }
        return new AnalysisResult($$parsedSource as Partial<AnalysisResult>);
    }
}

/**
 * Metadata carries per-analyzer plumbing (parser name, schema
 * version, parser diagnostics, findings list, AI interpretation
 * payload, etc.). `Findings` and `Extra` stay open-ended for the
 * same reason the section dicts above do.
 */
export type Metadata = any;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
