// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Summary {
    "applied": boolean;
    "version": string;
    "rules": string[];
    "counts": { [_ in string]?: number };

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("applied" in $$source)) {
            this["applied"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }
        if (!("counts" in $$source)) {
            this["counts"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        if ("counts" in $$parsedSource) {
            $$parsedSource["counts"] = $$createField3_0($$parsedSource["counts"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
