//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../aurakimjh/archscope/apps/profiler-native/cmd/archscope-profiler-app/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "analyze:cancelled": $$createType0,
        "analyze:done": $$createType1,
        "analyze:error": $$createType2,
        "engine:cancelled": $$createType3,
        "engine:done": $$createType4,
        "engine:error": $$createType5,
    }));
}

// Private type creation functions
const $$createType0 = main$0.AnalyzeCancelledEvent.createFrom;
const $$createType1 = main$0.AnalyzeDoneEvent.createFrom;
const $$createType2 = main$0.AnalyzeErrorEvent.createFrom;
const $$createType3 = main$0.EngineCancelledEvent.createFrom;
const $$createType4 = main$0.EngineDoneEvent.createFrom;
const $$createType5 = main$0.EngineErrorEvent.createFrom;

configure();
