// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../aurakimjh/archscope/apps/profiler-native/cmd/archscope-profiler-app/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "analyze:cancelled": main$0.AnalyzeCancelledEvent;
            "analyze:done": main$0.AnalyzeDoneEvent;
            "analyze:error": main$0.AnalyzeErrorEvent;
        }
    }
}
