// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AnalysisResult {
    "type": string;
    "source_files": string[];
    "created_at": string;
    "summary": Summary;
    "series": Series;
    "tables": Tables;
    "charts": Charts;
    "metadata": Metadata;

    /** Creates a new AnalysisResult instance. */
    constructor($$source: Partial<AnalysisResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source_files" in $$source)) {
            this["source_files"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new Summary());
        }
        if (!("series" in $$source)) {
            this["series"] = (new Series());
        }
        if (!("tables" in $$source)) {
            this["tables"] = (new Tables());
        }
        if (!("charts" in $$source)) {
            this["charts"] = (new Charts());
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = (new Metadata());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalysisResult {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_files" in $$parsedSource) {
            $$parsedSource["source_files"] = $$createField1_0($$parsedSource["source_files"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField4_0($$parsedSource["series"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("charts" in $$parsedSource) {
            $$parsedSource["charts"] = $$createField6_0($$parsedSource["charts"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new AnalysisResult($$parsedSource as Partial<AnalysisResult>);
    }
}

export class Charts {
    "flamegraph": FlameNode;
    "drilldown_stages": DrilldownStage[];

    /** Creates a new Charts instance. */
    constructor($$source: Partial<Charts> = {}) {
        if (!("flamegraph" in $$source)) {
            this["flamegraph"] = (new FlameNode());
        }
        if (!("drilldown_stages" in $$source)) {
            this["drilldown_stages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Charts instance from a string or object.
     */
    static createFrom($$source: any = {}): Charts {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flamegraph" in $$parsedSource) {
            $$parsedSource["flamegraph"] = $$createField0_0($$parsedSource["flamegraph"]);
        }
        if ("drilldown_stages" in $$parsedSource) {
            $$parsedSource["drilldown_stages"] = $$createField1_0($$parsedSource["drilldown_stages"]);
        }
        return new Charts($$parsedSource as Partial<Charts>);
    }
}

export class ComponentBreakdownRow {
    "component": string;
    "samples": number;

    /** Creates a new ComponentBreakdownRow instance. */
    constructor($$source: Partial<ComponentBreakdownRow> = {}) {
        if (!("component" in $$source)) {
            this["component"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentBreakdownRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ComponentBreakdownRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentBreakdownRow($$parsedSource as Partial<ComponentBreakdownRow>);
    }
}

export class DiagnosticSample {
    "line_number": number;
    "reason": string;
    "message": string;
    "raw_preview": string;

    /** Creates a new DiagnosticSample instance. */
    constructor($$source: Partial<DiagnosticSample> = {}) {
        if (!("line_number" in $$source)) {
            this["line_number"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("raw_preview" in $$source)) {
            this["raw_preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticSample instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticSample {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticSample($$parsedSource as Partial<DiagnosticSample>);
    }
}

/**
 * DrilldownFilter mirrors the Python `DrilldownFilter` dataclass.
 */
export class DrilldownFilter {
    "pattern": string;

    /**
     * include_text | exclude_text | regex_include | regex_exclude
     */
    "filter_type": string;

    /**
     * anywhere | ordered | subtree
     */
    "match_mode": string;

    /**
     * preserve_full_path | reroot_at_match
     */
    "view_mode": string;
    "case_sensitive": boolean;
    "label"?: string;

    /** Creates a new DrilldownFilter instance. */
    constructor($$source: Partial<DrilldownFilter> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("filter_type" in $$source)) {
            this["filter_type"] = "";
        }
        if (!("match_mode" in $$source)) {
            this["match_mode"] = "";
        }
        if (!("view_mode" in $$source)) {
            this["view_mode"] = "";
        }
        if (!("case_sensitive" in $$source)) {
            this["case_sensitive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrilldownFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): DrilldownFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DrilldownFilter($$parsedSource as Partial<DrilldownFilter>);
    }
}

export class DrilldownStage {
    "index": number;
    "label": string;
    "breadcrumb": string[];
    "filter": any;
    "metrics": { [_ in string]?: any };
    "flamegraph": FlameNode;
    "top_stacks": TopItem[];
    "top_child_frames": TopChildFrameRow[];
    "diagnostics": any;

    /** Creates a new DrilldownStage instance. */
    constructor($$source: Partial<DrilldownStage> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("breadcrumb" in $$source)) {
            this["breadcrumb"] = [];
        }
        if (!("filter" in $$source)) {
            this["filter"] = null;
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = {};
        }
        if (!("flamegraph" in $$source)) {
            this["flamegraph"] = (new FlameNode());
        }
        if (!("top_stacks" in $$source)) {
            this["top_stacks"] = [];
        }
        if (!("top_child_frames" in $$source)) {
            this["top_child_frames"] = [];
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrilldownStage instance from a string or object.
     */
    static createFrom($$source: any = {}): DrilldownStage {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("breadcrumb" in $$parsedSource) {
            $$parsedSource["breadcrumb"] = $$createField2_0($$parsedSource["breadcrumb"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField4_0($$parsedSource["metrics"]);
        }
        if ("flamegraph" in $$parsedSource) {
            $$parsedSource["flamegraph"] = $$createField5_0($$parsedSource["flamegraph"]);
        }
        if ("top_stacks" in $$parsedSource) {
            $$parsedSource["top_stacks"] = $$createField6_0($$parsedSource["top_stacks"]);
        }
        if ("top_child_frames" in $$parsedSource) {
            $$parsedSource["top_child_frames"] = $$createField7_0($$parsedSource["top_child_frames"]);
        }
        return new DrilldownStage($$parsedSource as Partial<DrilldownStage>);
    }
}

export class ExecutionBreakdownRow {
    "category": string;
    "executive_label": string;
    "primary_category": string;
    "wait_reason": string | null;
    "samples": number;
    "estimated_seconds": number;
    "total_ratio": number;
    "parent_stage_ratio": number;
    "elapsed_ratio": number | null;
    "top_methods": TopItem[];
    "top_stacks": TopItem[];

    /** Creates a new ExecutionBreakdownRow instance. */
    constructor($$source: Partial<ExecutionBreakdownRow> = {}) {
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("executive_label" in $$source)) {
            this["executive_label"] = "";
        }
        if (!("primary_category" in $$source)) {
            this["primary_category"] = "";
        }
        if (!("wait_reason" in $$source)) {
            this["wait_reason"] = null;
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("estimated_seconds" in $$source)) {
            this["estimated_seconds"] = 0;
        }
        if (!("total_ratio" in $$source)) {
            this["total_ratio"] = 0;
        }
        if (!("parent_stage_ratio" in $$source)) {
            this["parent_stage_ratio"] = 0;
        }
        if (!("elapsed_ratio" in $$source)) {
            this["elapsed_ratio"] = null;
        }
        if (!("top_methods" in $$source)) {
            this["top_methods"] = [];
        }
        if (!("top_stacks" in $$source)) {
            this["top_stacks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionBreakdownRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionBreakdownRow {
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_methods" in $$parsedSource) {
            $$parsedSource["top_methods"] = $$createField9_0($$parsedSource["top_methods"]);
        }
        if ("top_stacks" in $$parsedSource) {
            $$parsedSource["top_stacks"] = $$createField10_0($$parsedSource["top_stacks"]);
        }
        return new ExecutionBreakdownRow($$parsedSource as Partial<ExecutionBreakdownRow>);
    }
}

export class FlameNode {
    "id": string;
    "parentId": string | null;
    "name": string;
    "samples": number;
    "ratio": number;
    "category": string | null;
    "color": string | null;
    "children": FlameNode[];
    "metadata"?: any;

    /** Creates a new FlameNode instance. */
    constructor($$source: Partial<FlameNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }
        if (!("category" in $$source)) {
            this["category"] = null;
        }
        if (!("color" in $$source)) {
            this["color"] = null;
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlameNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FlameNode {
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        return new FlameNode($$parsedSource as Partial<FlameNode>);
    }
}

export class Metadata {
    "parser": string;
    "schema_version": string;
    "diagnostics": ParserDiagnostics;
    "timeline_scope": TimelineScope;

    /**
     * ProgressLogPath, when non-empty, points to the on-disk
     * streaming log written during parse + analyze. Surfaced to the
     * renderer so the user has a tailable artifact when a 400 MB
     * wall analysis crashes.
     */
    "progress_log_path"?: string;

    /**
     * Profiler-diff–specific payload. Empty for ordinary profiler results.
     */
    "diff_summary"?: { [_ in string]?: any };
    "diff_tables"?: { [_ in string]?: any };

    /** Creates a new Metadata instance. */
    constructor($$source: Partial<Metadata> = {}) {
        if (!("parser" in $$source)) {
            this["parser"] = "";
        }
        if (!("schema_version" in $$source)) {
            this["schema_version"] = "";
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = (new ParserDiagnostics());
        }
        if (!("timeline_scope" in $$source)) {
            this["timeline_scope"] = (new TimelineScope());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     */
    static createFrom($$source: any = {}): Metadata {
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType16;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField2_0($$parsedSource["diagnostics"]);
        }
        if ("timeline_scope" in $$parsedSource) {
            $$parsedSource["timeline_scope"] = $$createField3_0($$parsedSource["timeline_scope"]);
        }
        if ("diff_summary" in $$parsedSource) {
            $$parsedSource["diff_summary"] = $$createField5_0($$parsedSource["diff_summary"]);
        }
        if ("diff_tables" in $$parsedSource) {
            $$parsedSource["diff_tables"] = $$createField6_0($$parsedSource["diff_tables"]);
        }
        return new Metadata($$parsedSource as Partial<Metadata>);
    }
}

export class ParserDiagnostics {
    "source_file": string | null;
    "format": string;
    "total_lines": number;
    "parsed_records": number;
    "skipped_lines": number;
    "skipped_by_reason": { [_ in string]?: number };
    "samples": DiagnosticSample[];
    "warning_count": number;
    "error_count": number;
    "warnings": DiagnosticSample[];
    "errors": DiagnosticSample[];

    /**
     * Memory-guard counters (T-WALL70). Populated when caps in
     * Options trigger; rendered in the parser-report tab so the user
     * can see exactly what the analyzer dropped to stay within budget.
     */
    "dropped_stacks"?: number;
    "dropped_stack_reason"?: string;
    "over_depth_records"?: number;
    "max_observed_depth"?: number;
    "bytes_read"?: number;

    /** Creates a new ParserDiagnostics instance. */
    constructor($$source: Partial<ParserDiagnostics> = {}) {
        if (!("source_file" in $$source)) {
            this["source_file"] = null;
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("total_lines" in $$source)) {
            this["total_lines"] = 0;
        }
        if (!("parsed_records" in $$source)) {
            this["parsed_records"] = 0;
        }
        if (!("skipped_lines" in $$source)) {
            this["skipped_lines"] = 0;
        }
        if (!("skipped_by_reason" in $$source)) {
            this["skipped_by_reason"] = {};
        }
        if (!("samples" in $$source)) {
            this["samples"] = [];
        }
        if (!("warning_count" in $$source)) {
            this["warning_count"] = 0;
        }
        if (!("error_count" in $$source)) {
            this["error_count"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParserDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): ParserDiagnostics {
        const $$createField5_0 = $$createType17;
        const $$createField6_0 = $$createType19;
        const $$createField9_0 = $$createType19;
        const $$createField10_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skipped_by_reason" in $$parsedSource) {
            $$parsedSource["skipped_by_reason"] = $$createField5_0($$parsedSource["skipped_by_reason"]);
        }
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField6_0($$parsedSource["samples"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField9_0($$parsedSource["warnings"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField10_0($$parsedSource["errors"]);
        }
        return new ParserDiagnostics($$parsedSource as Partial<ParserDiagnostics>);
    }
}

export class Series {
    "top_stacks": TopStackSeriesRow[];
    "component_breakdown": ComponentBreakdownRow[];
    "execution_breakdown": ExecutionBreakdownRow[];
    "timeline_analysis": TimelineRow[];
    "threads": ThreadRow[];

    /** Creates a new Series instance. */
    constructor($$source: Partial<Series> = {}) {
        if (!("top_stacks" in $$source)) {
            this["top_stacks"] = [];
        }
        if (!("component_breakdown" in $$source)) {
            this["component_breakdown"] = [];
        }
        if (!("execution_breakdown" in $$source)) {
            this["execution_breakdown"] = [];
        }
        if (!("timeline_analysis" in $$source)) {
            this["timeline_analysis"] = [];
        }
        if (!("threads" in $$source)) {
            this["threads"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Series instance from a string or object.
     */
    static createFrom($$source: any = {}): Series {
        const $$createField0_0 = $$createType21;
        const $$createField1_0 = $$createType23;
        const $$createField2_0 = $$createType25;
        const $$createField3_0 = $$createType27;
        const $$createField4_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_stacks" in $$parsedSource) {
            $$parsedSource["top_stacks"] = $$createField0_0($$parsedSource["top_stacks"]);
        }
        if ("component_breakdown" in $$parsedSource) {
            $$parsedSource["component_breakdown"] = $$createField1_0($$parsedSource["component_breakdown"]);
        }
        if ("execution_breakdown" in $$parsedSource) {
            $$parsedSource["execution_breakdown"] = $$createField2_0($$parsedSource["execution_breakdown"]);
        }
        if ("timeline_analysis" in $$parsedSource) {
            $$parsedSource["timeline_analysis"] = $$createField3_0($$parsedSource["timeline_analysis"]);
        }
        if ("threads" in $$parsedSource) {
            $$parsedSource["threads"] = $$createField4_0($$parsedSource["threads"]);
        }
        return new Series($$parsedSource as Partial<Series>);
    }
}

export class Summary {
    "profile_kind": string;
    "total_samples": number;
    "interval_ms": number;
    "estimated_seconds": number;
    "elapsed_seconds": number | null;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("profile_kind" in $$source)) {
            this["profile_kind"] = "";
        }
        if (!("total_samples" in $$source)) {
            this["total_samples"] = 0;
        }
        if (!("interval_ms" in $$source)) {
            this["interval_ms"] = 0;
        }
        if (!("estimated_seconds" in $$source)) {
            this["estimated_seconds"] = 0;
        }
        if (!("elapsed_seconds" in $$source)) {
            this["elapsed_seconds"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

export class Tables {
    "top_stacks": TopStackTableRow[];
    "top_child_frames": TopChildFrameRow[];
    "timeline_analysis": TimelineRow[];

    /** Creates a new Tables instance. */
    constructor($$source: Partial<Tables> = {}) {
        if (!("top_stacks" in $$source)) {
            this["top_stacks"] = [];
        }
        if (!("top_child_frames" in $$source)) {
            this["top_child_frames"] = [];
        }
        if (!("timeline_analysis" in $$source)) {
            this["timeline_analysis"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tables instance from a string or object.
     */
    static createFrom($$source: any = {}): Tables {
        const $$createField0_0 = $$createType31;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_stacks" in $$parsedSource) {
            $$parsedSource["top_stacks"] = $$createField0_0($$parsedSource["top_stacks"]);
        }
        if ("top_child_frames" in $$parsedSource) {
            $$parsedSource["top_child_frames"] = $$createField1_0($$parsedSource["top_child_frames"]);
        }
        if ("timeline_analysis" in $$parsedSource) {
            $$parsedSource["timeline_analysis"] = $$createField2_0($$parsedSource["timeline_analysis"]);
        }
        return new Tables($$parsedSource as Partial<Tables>);
    }
}

export class ThreadRow {
    "name": string;
    "samples": number;
    "ratio": number;

    /** Creates a new ThreadRow instance. */
    constructor($$source: Partial<ThreadRow> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadRow instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadRow($$parsedSource as Partial<ThreadRow>);
    }
}

export class TimelineChainRow {
    "chain": string;
    "samples": number;
    "frames": string[];

    /** Creates a new TimelineChainRow instance. */
    constructor($$source: Partial<TimelineChainRow> = {}) {
        if (!("chain" in $$source)) {
            this["chain"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("frames" in $$source)) {
            this["frames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineChainRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineChainRow {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField2_0($$parsedSource["frames"]);
        }
        return new TimelineChainRow($$parsedSource as Partial<TimelineChainRow>);
    }
}

export class TimelineRow {
    "index": number;
    "segment": string;
    "label": string;
    "samples": number;
    "estimated_seconds": number;
    "stage_ratio": number;
    "total_ratio": number;
    "elapsed_ratio": number | null;
    "top_methods": TopItem[];
    "method_chains": TimelineChainRow[];
    "top_stacks": TopItem[];

    /** Creates a new TimelineRow instance. */
    constructor($$source: Partial<TimelineRow> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("segment" in $$source)) {
            this["segment"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("estimated_seconds" in $$source)) {
            this["estimated_seconds"] = 0;
        }
        if (!("stage_ratio" in $$source)) {
            this["stage_ratio"] = 0;
        }
        if (!("total_ratio" in $$source)) {
            this["total_ratio"] = 0;
        }
        if (!("elapsed_ratio" in $$source)) {
            this["elapsed_ratio"] = null;
        }
        if (!("top_methods" in $$source)) {
            this["top_methods"] = [];
        }
        if (!("method_chains" in $$source)) {
            this["method_chains"] = [];
        }
        if (!("top_stacks" in $$source)) {
            this["top_stacks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineRow {
        const $$createField8_0 = $$createType11;
        const $$createField9_0 = $$createType33;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_methods" in $$parsedSource) {
            $$parsedSource["top_methods"] = $$createField8_0($$parsedSource["top_methods"]);
        }
        if ("method_chains" in $$parsedSource) {
            $$parsedSource["method_chains"] = $$createField9_0($$parsedSource["method_chains"]);
        }
        if ("top_stacks" in $$parsedSource) {
            $$parsedSource["top_stacks"] = $$createField10_0($$parsedSource["top_stacks"]);
        }
        return new TimelineRow($$parsedSource as Partial<TimelineRow>);
    }
}

export class TimelineScope {
    "mode": string;
    "base_method": string | null;
    "match_mode": string;
    "view_mode": string;
    "base_samples": number;
    "total_samples": number;
    "base_ratio_of_total": number | null;
    "warnings": TimelineWarning[];

    /** Creates a new TimelineScope instance. */
    constructor($$source: Partial<TimelineScope> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("base_method" in $$source)) {
            this["base_method"] = null;
        }
        if (!("match_mode" in $$source)) {
            this["match_mode"] = "";
        }
        if (!("view_mode" in $$source)) {
            this["view_mode"] = "";
        }
        if (!("base_samples" in $$source)) {
            this["base_samples"] = 0;
        }
        if (!("total_samples" in $$source)) {
            this["total_samples"] = 0;
        }
        if (!("base_ratio_of_total" in $$source)) {
            this["base_ratio_of_total"] = null;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineScope instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineScope {
        const $$createField7_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new TimelineScope($$parsedSource as Partial<TimelineScope>);
    }
}

export class TimelineWarning {
    "code": string;
    "message": string;

    /** Creates a new TimelineWarning instance. */
    constructor($$source: Partial<TimelineWarning> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineWarning instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineWarning {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimelineWarning($$parsedSource as Partial<TimelineWarning>);
    }
}

export class TopChildFrameRow {
    "frame": string;
    "samples": number;
    "ratio": number;

    /** Creates a new TopChildFrameRow instance. */
    constructor($$source: Partial<TopChildFrameRow> = {}) {
        if (!("frame" in $$source)) {
            this["frame"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopChildFrameRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TopChildFrameRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopChildFrameRow($$parsedSource as Partial<TopChildFrameRow>);
    }
}

export class TopItem {
    "name": string;
    "samples": number;

    /** Creates a new TopItem instance. */
    constructor($$source: Partial<TopItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopItem($$parsedSource as Partial<TopItem>);
    }
}

export class TopStackSeriesRow {
    "stack": string;
    "samples": number;
    "estimated_seconds": number;
    "sample_ratio": number;
    "elapsed_ratio": number | null;

    /** Creates a new TopStackSeriesRow instance. */
    constructor($$source: Partial<TopStackSeriesRow> = {}) {
        if (!("stack" in $$source)) {
            this["stack"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("estimated_seconds" in $$source)) {
            this["estimated_seconds"] = 0;
        }
        if (!("sample_ratio" in $$source)) {
            this["sample_ratio"] = 0;
        }
        if (!("elapsed_ratio" in $$source)) {
            this["elapsed_ratio"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopStackSeriesRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TopStackSeriesRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopStackSeriesRow($$parsedSource as Partial<TopStackSeriesRow>);
    }
}

export class TopStackTableRow {
    "stack": string;
    "samples": number;
    "estimated_seconds": number;
    "sample_ratio": number;
    "elapsed_ratio": number | null;
    "frames": string[];

    /** Creates a new TopStackTableRow instance. */
    constructor($$source: Partial<TopStackTableRow> = {}) {
        if (!("stack" in $$source)) {
            this["stack"] = "";
        }
        if (!("samples" in $$source)) {
            this["samples"] = 0;
        }
        if (!("estimated_seconds" in $$source)) {
            this["estimated_seconds"] = 0;
        }
        if (!("sample_ratio" in $$source)) {
            this["sample_ratio"] = 0;
        }
        if (!("elapsed_ratio" in $$source)) {
            this["elapsed_ratio"] = null;
        }
        if (!("frames" in $$source)) {
            this["frames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopStackTableRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TopStackTableRow {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField5_0($$parsedSource["frames"]);
        }
        return new TopStackTableRow($$parsedSource as Partial<TopStackTableRow>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Summary.createFrom;
const $$createType2 = Series.createFrom;
const $$createType3 = Tables.createFrom;
const $$createType4 = Charts.createFrom;
const $$createType5 = Metadata.createFrom;
const $$createType6 = FlameNode.createFrom;
const $$createType7 = DrilldownStage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = TopItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = TopChildFrameRow.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($$createType6);
const $$createType15 = ParserDiagnostics.createFrom;
const $$createType16 = TimelineScope.createFrom;
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = DiagnosticSample.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = TopStackSeriesRow.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ComponentBreakdownRow.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ExecutionBreakdownRow.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = TimelineRow.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = ThreadRow.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = TopStackTableRow.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = TimelineChainRow.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = TimelineWarning.createFrom;
const $$createType35 = $Create.Array($$createType34);
