// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class Config {
    "listenAddress"?: string;
    "storeRoot"?: string;
    "maxSessionBytes"?: number;
    "reserveBytes"?: number;
    "bodyFraction"?: number;
    "overflowPolicy"?: OverflowPolicy;
    "writeHighWaterBytes"?: number;
    "writeHardLimitBytes"?: number;
    "liveWindow"?: number;
    "allowPassthrough"?: string[];
    "passthroughTtlSeconds"?: number;
    "retainUnattributedMetadata"?: boolean;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowPassthrough" in $$parsedSource) {
            $$parsedSource["allowPassthrough"] = $$createField9_0($$parsedSource["allowPassthrough"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class LiveCaptureContract {
    "schemaVersion": number;
    "transactionRowCap": number;
    "resyncOnEventSkip": boolean;
    "restoreCurrentSessionOnPageReentry": boolean;
    "finalizedSessionUsesAnalysisResult": boolean;

    /** Creates a new LiveCaptureContract instance. */
    constructor($$source: Partial<LiveCaptureContract> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("transactionRowCap" in $$source)) {
            this["transactionRowCap"] = 0;
        }
        if (!("resyncOnEventSkip" in $$source)) {
            this["resyncOnEventSkip"] = false;
        }
        if (!("restoreCurrentSessionOnPageReentry" in $$source)) {
            this["restoreCurrentSessionOnPageReentry"] = false;
        }
        if (!("finalizedSessionUsesAnalysisResult" in $$source)) {
            this["finalizedSessionUsesAnalysisResult"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveCaptureContract instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveCaptureContract {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveCaptureContract($$parsedSource as Partial<LiveCaptureContract>);
    }
}

export class Mode {
    "name": string;
    "available": boolean;
    "reason"?: string;
    "requiredPrivilege": Privilege;
    "fidelity": string;

    /** Creates a new Mode instance. */
    constructor($$source: Partial<Mode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("requiredPrivilege" in $$source)) {
            this["requiredPrivilege"] = Privilege.$zero;
        }
        if (!("fidelity" in $$source)) {
            this["fidelity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mode instance from a string or object.
     */
    static createFrom($$source: any = {}): Mode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mode($$parsedSource as Partial<Mode>);
    }
}

export enum OverflowPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OverflowStop = "stop",
    OverflowBodyOnly = "body_only",
    OverflowRotate = "rotate",
};

export enum Privilege {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PrivilegeNone = "none",
    PrivilegeAdmin = "admin",
};

export class Session {
    "sessionId": SessionID;
    "state": SessionState;
    "listenAddress": string;
    "storePath": string;
    "startedAt": time$0.Time;
    "endedAt"?: time$0.Time | null;
    "error"?: string;
    "retainUnattributedMetadata": boolean;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = SessionState.$zero;
        }
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }
        if (!("storePath" in $$source)) {
            this["storePath"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("retainUnattributedMetadata" in $$source)) {
            this["retainUnattributedMetadata"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

export type SessionID = string;

export enum SessionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateCreated = "created",
    StateStarting = "starting",
    StateRunning = "running",
    StateStopping = "stopping",
    StateFinalized = "finalized",
    StateFailed = "failed",
    StateRecoverable = "recoverable",
};

export class Stats {
    "sessionId": SessionID;
    "state": SessionState;
    "observed": number;
    "captured": number;
    "persisted": number;
    "bodyOmitted": number;
    "eventSkipped": number;
    "kernelDropped": number;
    "parseFailed": number;
    "unsupported": number;
    "passthrough": number;
    "unattributed": number;
    "dropped": number;
    "backpressured": boolean;
    "snapshotVersion": number;
    "sequence": number;
    "storeBytes": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = SessionState.$zero;
        }
        if (!("observed" in $$source)) {
            this["observed"] = 0;
        }
        if (!("captured" in $$source)) {
            this["captured"] = 0;
        }
        if (!("persisted" in $$source)) {
            this["persisted"] = 0;
        }
        if (!("bodyOmitted" in $$source)) {
            this["bodyOmitted"] = 0;
        }
        if (!("eventSkipped" in $$source)) {
            this["eventSkipped"] = 0;
        }
        if (!("kernelDropped" in $$source)) {
            this["kernelDropped"] = 0;
        }
        if (!("parseFailed" in $$source)) {
            this["parseFailed"] = 0;
        }
        if (!("unsupported" in $$source)) {
            this["unsupported"] = 0;
        }
        if (!("passthrough" in $$source)) {
            this["passthrough"] = 0;
        }
        if (!("unattributed" in $$source)) {
            this["unattributed"] = 0;
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }
        if (!("backpressured" in $$source)) {
            this["backpressured"] = false;
        }
        if (!("snapshotVersion" in $$source)) {
            this["snapshotVersion"] = 0;
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("storeBytes" in $$source)) {
            this["storeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
