// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../models/models.js";

export class Filter {
    "host"?: string;
    "method"?: string;
    "statusCode"?: number;
    "processId"?: number;
    "errorsOnly"?: boolean;

    /** Creates a new Filter instance. */
    constructor($$source: Partial<Filter> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filter instance from a string or object.
     */
    static createFrom($$source: any = {}): Filter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Filter($$parsedSource as Partial<Filter>);
    }
}

export class Page {
    "items": StoredTransaction[];
    "nextCursor"?: string;
    "snapshotVersion": number;
    "total": number;

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("snapshotVersion" in $$source)) {
            this["snapshotVersion"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Page instance from a string or object.
     */
    static createFrom($$source: any = {}): Page {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new Page($$parsedSource as Partial<Page>);
    }
}

export class RecoveryReport {
    "recovered": boolean;
    "discardedBytes": number;
    "records": number;

    /** Creates a new RecoveryReport instance. */
    constructor($$source: Partial<RecoveryReport> = {}) {
        if (!("recovered" in $$source)) {
            this["recovered"] = false;
        }
        if (!("discardedBytes" in $$source)) {
            this["discardedBytes"] = 0;
        }
        if (!("records" in $$source)) {
            this["records"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecoveryReport instance from a string or object.
     */
    static createFrom($$source: any = {}): RecoveryReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecoveryReport($$parsedSource as Partial<RecoveryReport>);
    }
}

export class StoredTransaction {
    "seq": number;
    "transaction": models$0.CaptureTransaction;

    /** Creates a new StoredTransaction instance. */
    constructor($$source: Partial<StoredTransaction> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("transaction" in $$source)) {
            this["transaction"] = (new models$0.CaptureTransaction());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredTransaction instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredTransaction {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transaction" in $$parsedSource) {
            $$parsedSource["transaction"] = $$createField1_0($$parsedSource["transaction"]);
        }
        return new StoredTransaction($$parsedSource as Partial<StoredTransaction>);
    }
}

// Private type creation functions
const $$createType0 = StoredTransaction.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.CaptureTransaction.createFrom;
