// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../aurakimjh/archscope/apps/engine-native/cmd/archscope-app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as capture$0 from "../../../../aurakimjh/archscope/apps/engine-native/internal/capture/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "analyze:cancelled": main$0.AnalyzeCancelledEvent;
            "analyze:done": main$0.AnalyzeDoneEvent;
            "analyze:error": main$0.AnalyzeErrorEvent;
            "capture:aggregate": main$0.CaptureAggregateEvent;
            "capture:error": main$0.CaptureErrorEvent;
            "capture:started": capture$0.Session;
            "capture:stats": capture$0.Stats;
            "capture:stopped": capture$0.Session;
            "capture:transactions": main$0.CaptureTransactionsEvent;
            "engine:cancelled": main$0.EngineCancelledEvent;
            "engine:done": main$0.EngineDoneEvent;
            "engine:error": main$0.EngineErrorEvent;
        }
    }
}
