// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "../models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as redact$0 from "../redact/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../models/models.js";

export class Evidence {
    "schemaVersion": number;
    "task": string;
    "generatedAt": string;
    "session": SessionEvidence;
    "stats": capture$0.Stats;
    "redaction": redact$0.Summary;
    "liveContract": capture$0.LiveCaptureContract;
    "counts": { [_ in string]?: number };
    "rows": Row[];
    "rowsTruncated": boolean;

    /** Creates a new Evidence instance. */
    constructor($$source: Partial<Evidence> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("session" in $$source)) {
            this["session"] = (new SessionEvidence());
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new capture$0.Stats());
        }
        if (!("redaction" in $$source)) {
            this["redaction"] = (new redact$0.Summary());
        }
        if (!("liveContract" in $$source)) {
            this["liveContract"] = (new capture$0.LiveCaptureContract());
        }
        if (!("counts" in $$source)) {
            this["counts"] = {};
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowsTruncated" in $$source)) {
            this["rowsTruncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Evidence instance from a string or object.
     */
    static createFrom($$source: any = {}): Evidence {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField3_0($$parsedSource["session"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField4_0($$parsedSource["stats"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField5_0($$parsedSource["redaction"]);
        }
        if ("liveContract" in $$parsedSource) {
            $$parsedSource["liveContract"] = $$createField6_0($$parsedSource["liveContract"]);
        }
        if ("counts" in $$parsedSource) {
            $$parsedSource["counts"] = $$createField7_0($$parsedSource["counts"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField8_0($$parsedSource["rows"]);
        }
        return new Evidence($$parsedSource as Partial<Evidence>);
    }
}

export class Row {
    "id": string;
    "method": string;
    "url": string;
    "scheme": string;
    "host": string;
    "path": string;
    "statusCode": number;
    "state": models$0.TxState;
    "error"?: string;
    "captureMode": string;
    "fidelity": string;
    "coverage": string;
    "processName"?: string;
    "processAttribution"?: string;
    "requestBodyStorage": string;
    "responseBodyStorage": string;

    /** Creates a new Row instance. */
    constructor($$source: Partial<Row> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = models$0.TxState.$zero;
        }
        if (!("captureMode" in $$source)) {
            this["captureMode"] = "";
        }
        if (!("fidelity" in $$source)) {
            this["fidelity"] = "";
        }
        if (!("coverage" in $$source)) {
            this["coverage"] = "";
        }
        if (!("requestBodyStorage" in $$source)) {
            this["requestBodyStorage"] = "";
        }
        if (!("responseBodyStorage" in $$source)) {
            this["responseBodyStorage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Row instance from a string or object.
     */
    static createFrom($$source: any = {}): Row {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Row($$parsedSource as Partial<Row>);
    }
}

export class SessionEvidence {
    "sessionId": string;
    "state": capture$0.SessionState;
    "snapshotVersion": number;
    "storeBytes": number;
    "totalRows": number;

    /** Creates a new SessionEvidence instance. */
    constructor($$source: Partial<SessionEvidence> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = capture$0.SessionState.$zero;
        }
        if (!("snapshotVersion" in $$source)) {
            this["snapshotVersion"] = 0;
        }
        if (!("storeBytes" in $$source)) {
            this["storeBytes"] = 0;
        }
        if (!("totalRows" in $$source)) {
            this["totalRows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEvidence instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEvidence {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionEvidence($$parsedSource as Partial<SessionEvidence>);
    }
}

// Private type creation functions
const $$createType0 = SessionEvidence.createFrom;
const $$createType1 = capture$0.Stats.createFrom;
const $$createType2 = redact$0.Summary.createFrom;
const $$createType3 = capture$0.LiveCaptureContract.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = Row.createFrom;
const $$createType6 = $Create.Array($$createType5);
