// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AnalysisResult is the universal envelope. Each analyzer populates
 * only the fields it needs; the rest stay as their zero value.
 * 
 * `Series` / `Tables` / `Charts` / `Summary` are kept as
 * `map[string]any` rather than typed structs because the Python
 * implementation projects different shapes per analyzer (access log
 * = per-minute timeline; profiler = flame tree; thread dump = state
 * distribution). The renderer uses the `Type` field to decide which
 * keys to look for; the parity job just diffs the JSON.
 * 
 * [한글] 필드별 의미
 *   Type        : 분석기 식별자(예: "access_log", "thread_dump_multi").
 *                 UI 가 어떤 페이지·차트로 렌더할지 결정.
 *   SourceFiles : 분석기가 받은 입력 파일 경로들. 보고서에 출처를
 *                 표시할 때 사용.
 *   CreatedAt   : RFC3339Nano. parity gate 비교에서 노이즈가 되지
 *                 않도록 분석기 호출 직전이 아닌 결과 생성 시점.
 *   Summary     : 메트릭 카드(상단 KPI)에 표시할 스칼라 모음.
 *   Series      : 차트 시계열/배열 데이터.
 *   Tables      : shadcn/D3 표용 행 모음.
 *   Charts      : flame tree 같은 raw 차트 데이터.
 *   Metadata    : 파서·진단·findings 등 부수 정보(아래 참고).
 */
export class AnalysisResult {
    "type": string;
    "source_files": string[];
    "created_at": string;
    "summary": { [_ in string]?: any };
    "series": { [_ in string]?: any };
    "tables": { [_ in string]?: any };
    "charts": { [_ in string]?: any };
    "metadata": Metadata;

    /** Creates a new AnalysisResult instance. */
    constructor($$source: Partial<AnalysisResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source_files" in $$source)) {
            this["source_files"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = {};
        }
        if (!("series" in $$source)) {
            this["series"] = {};
        }
        if (!("tables" in $$source)) {
            this["tables"] = {};
        }
        if (!("charts" in $$source)) {
            this["charts"] = {};
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalysisResult {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source_files" in $$parsedSource) {
            $$parsedSource["source_files"] = $$createField1_0($$parsedSource["source_files"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField4_0($$parsedSource["series"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("charts" in $$parsedSource) {
            $$parsedSource["charts"] = $$createField6_0($$parsedSource["charts"]);
        }
        return new AnalysisResult($$parsedSource as Partial<AnalysisResult>);
    }
}

/**
 * JenniferCustomAnalysisRule is a user-defined roll-up bucket. Source controls
 * which profile surface is matched: profile_application uses the profile URL
 * and charges the whole profile response time; method matches body method/event
 * text and charges exclusive internal elapsed; external_call_url matches
 * EXTERNAL_CALL URL.
 */
export class JenniferCustomAnalysisRule {
    "id"?: string;
    "label": string;
    "group"?: string;
    "source": string;
    "patterns": string[];

    /** Creates a new JenniferCustomAnalysisRule instance. */
    constructor($$source: Partial<JenniferCustomAnalysisRule> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("patterns" in $$source)) {
            this["patterns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JenniferCustomAnalysisRule instance from a string or object.
     */
    static createFrom($$source: any = {}): JenniferCustomAnalysisRule {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("patterns" in $$parsedSource) {
            $$parsedSource["patterns"] = $$createField4_0($$parsedSource["patterns"]);
        }
        return new JenniferCustomAnalysisRule($$parsedSource as Partial<JenniferCustomAnalysisRule>);
    }
}

/**
 * Metadata carries per-analyzer plumbing (parser name, schema
 * version, parser diagnostics, findings list, AI interpretation
 * payload, etc.). `Findings` and `Extra` stay open-ended for the
 * same reason the section dicts above do.
 */
export type Metadata = any;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
