// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../../time/models.js";

export class Row {
    "key": string;
    "count": number;
    "errors": number;
    "total_duration_ms": number;
    "response_bytes": number;

    /** Creates a new Row instance. */
    constructor($$source: Partial<Row> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = 0;
        }
        if (!("total_duration_ms" in $$source)) {
            this["total_duration_ms"] = 0;
        }
        if (!("response_bytes" in $$source)) {
            this["response_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Row instance from a string or object.
     */
    static createFrom($$source: any = {}): Row {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Row($$parsedSource as Partial<Row>);
    }
}

export class Snapshot {
    "session_id": string;
    "snapshot_version": number;
    "sequence": number;
    "generated_at": time$0.Time;
    "total": number;
    "errors": number;
    "top_endpoints": Row[];
    "top_hosts": Row[];

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("snapshot_version" in $$source)) {
            this["snapshot_version"] = 0;
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("generated_at" in $$source)) {
            this["generated_at"] = null;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = 0;
        }
        if (!("top_endpoints" in $$source)) {
            this["top_endpoints"] = [];
        }
        if (!("top_hosts" in $$source)) {
            this["top_hosts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_endpoints" in $$parsedSource) {
            $$parsedSource["top_endpoints"] = $$createField6_0($$parsedSource["top_endpoints"]);
        }
        if ("top_hosts" in $$parsedSource) {
            $$parsedSource["top_hosts"] = $$createField7_0($$parsedSource["top_hosts"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

// Private type creation functions
const $$createType0 = Row.createFrom;
const $$createType1 = $Create.Array($$createType0);
