// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/models/models.js";

/**
 * AnalysisResult is the universal envelope every analyzer emits.
 */
export const AnalysisResult = models$0.AnalysisResult;

/**
 * AnalysisResult is the universal envelope every analyzer emits.
 */
export type AnalysisResult = models$0.AnalysisResult;
