// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService exposes the Tier-3/4 analyzers and exporters from
 * apps/engine-native to the Wails renderer. The engine packages are
 * stateless per-call (they take a path / bundle slice and return an
 * AnalysisResult), so the service holds no fields. The Wails binding
 * generator picks up exported methods on this type and emits matching
 * TypeScript signatures under
 * `frontend/bindings/.../engineservice.ts`.
 * 
 * Sync vs async split: any analyzer that walks multiple files or builds
 * N-way correlations (multithread, lockcontention) returns immediately
 * with an EngineAsyncResponse{TaskID} and reports completion via the
 * engine:done / engine:error / engine:cancelled events. Single-file
 * analyzers are synchronous because the µs–ms cost wouldn't justify the
 * round-trip ceremony.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../../engine-native/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../engine-native/internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeAccessLog wraps engineapi.AnalyzeAccessLog. RFC3339 strings
 * on the request are parsed once and forwarded as *time.Time.
 */
export function AnalyzeAccessLog(req: $models.AccessLogRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(1960996887, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeException wraps engineapi.AnalyzeException.
 */
export function AnalyzeException(req: $models.ExceptionRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(3396329610, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeGcLog wraps engineapi.AnalyzeGcLog.
 */
export function AnalyzeGcLog(req: $models.GcLogRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(797849915, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeJenniferProfile wraps engineapi.AnalyzeJenniferProfile/s.
 * Either Path (single) or Paths (batch) must be provided; if both
 * are set, Paths wins.
 */
export function AnalyzeJenniferProfile(req: $models.JenniferProfileRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(3749926873, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeJfr wraps engineapi.AnalyzeJfr.
 */
export function AnalyzeJfr(req: $models.JfrRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(2738048237, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeLockContention is the lock-contention analog of AnalyzeMultiThread.
 */
export function AnalyzeLockContention(req: $models.LockContentionRequest): $CancellablePromise<$models.EngineAsyncResponse> {
    return $Call.ByID(3950840739, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AnalyzeMultiThread parses every path in `req.Paths` through the
 * engine plugin registry and runs the multithread correlator. Async
 * because plugin sniffing + N-way correlation can run for hundreds of
 * ms on real-world dumps.
 */
export function AnalyzeMultiThread(req: $models.MultiThreadRequest): $CancellablePromise<$models.EngineAsyncResponse> {
    return $Call.ByID(2580349754, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AnalyzeNativeMemory wraps engineapi.AnalyzeJfrNativeMemory.
 */
export function AnalyzeNativeMemory(req: $models.JfrRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(68926921, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeOtel wraps engineapi.AnalyzeOtel.
 */
export function AnalyzeOtel(req: $models.OtelRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(2612578331, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeRuntimeStack dispatches to one of the four runtime variants
 * based on Variant. Empty Variant falls back to "nodejs".
 */
export function AnalyzeRuntimeStack(req: $models.RuntimeRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(866070465, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeThreadDump wraps engineapi.AnalyzeThreadDump (single Java
 * jstack file).
 */
export function AnalyzeThreadDump(req: $models.ThreadDumpRequest): $CancellablePromise<api$0.AnalysisResult> {
    return $Call.ByID(1802405455, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CancelEngineTask is the engine-side cancel hook. ProfilerService.Cancel
 * already covers profiler tasks; the registry is shared so either name
 * works, but a separate method keeps the binding name self-documenting.
 */
export function CancelEngineTask(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(342848350, taskID);
}

/**
 * ClassifyStack wraps engineapi.ClassifyStack. The package-level
 * default rules are used (matches Python's `rules=None`).
 */
export function ClassifyStack(req: $models.ClassifyRequest): $CancellablePromise<$models.ClassifyResult> {
    return $Call.ByID(2929597827, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConvertToCollapsed parses each path through the engine plugin
 * registry and folds the snapshots into the FlameGraph collapsed
 * format. Returns counts + sorted lines so the renderer can pick its
 * preferred shape.
 */
export function ConvertToCollapsed(req: $models.CollapsedRequest): $CancellablePromise<$models.CollapsedResult> {
    return $Call.ByID(1593102112, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DiffReports loads two AnalysisResult JSON files from disk and
 * returns the comparison_report payload. Mirrors Python's
 * build_comparison_report.
 */
export function DiffReports(req: $models.EngineDiffRequest): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3841388367, req).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ExportCSV writes a single CSV with section headers to `Path`.
 */
export function ExportCSV(req: $models.ExportCSVRequest): $CancellablePromise<void> {
    return $Call.ByID(3690322503, req);
}

/**
 * ExportCSVDir is the directory-mode variant — one CSV per logical
 * table under the directory at `Path`.
 */
export function ExportCSVDir(req: $models.ExportCSVRequest): $CancellablePromise<void> {
    return $Call.ByID(3982576166, req);
}

/**
 * ExportHTML renders `Result` as a static HTML page at `Path`.
 */
export function ExportHTML(req: $models.ExportHTMLRequest): $CancellablePromise<void> {
    return $Call.ByID(2263051608, req);
}

/**
 * ExportJSON marshals `Result` and writes it to `Path`.
 */
export function ExportJSON(req: $models.ExportJSONRequest): $CancellablePromise<void> {
    return $Call.ByID(240133483, req);
}

/**
 * ExportPPTX renders `Result` as a slide deck at `Path`.
 */
export function ExportPPTX(req: $models.ExportPPTXRequest): $CancellablePromise<void> {
    return $Call.ByID(3708449921, req);
}

// Private type creation functions
const $$createType0 = models$0.AnalysisResult.createFrom;
const $$createType1 = $models.EngineAsyncResponse.createFrom;
const $$createType2 = $models.ClassifyResult.createFrom;
const $$createType3 = $models.CollapsedResult.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
