// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiler$0 from "../../internal/profiler/models.js";

export class AnalyzeRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;

    /** Creates a new AnalyzeRequest instance. */
    constructor($$source: Partial<AnalyzeRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeRequest($$parsedSource as Partial<AnalyzeRequest>);
    }
}

export class DiffRequest {
    "baselinePath": string;
    "targetPath": string;
    "baselineFormat": string;
    "targetFormat": string;
    "intervalMs": number;
    "topN": number;
    "normalize": boolean;

    /** Creates a new DiffRequest instance. */
    constructor($$source: Partial<DiffRequest> = {}) {
        if (!("baselinePath" in $$source)) {
            this["baselinePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }
        if (!("baselineFormat" in $$source)) {
            this["baselineFormat"] = "";
        }
        if (!("targetFormat" in $$source)) {
            this["targetFormat"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("normalize" in $$source)) {
            this["normalize"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffRequest($$parsedSource as Partial<DiffRequest>);
    }
}

export class DrilldownRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;
    "filters": profiler$0.DrilldownFilter[];

    /** Creates a new DrilldownRequest instance. */
    constructor($$source: Partial<DrilldownRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }
        if (!("filters" in $$source)) {
            this["filters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrilldownRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DrilldownRequest {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField7_0($$parsedSource["filters"]);
        }
        return new DrilldownRequest($$parsedSource as Partial<DrilldownRequest>);
    }
}

export class ExportPprofRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;
    "outputPath": string;

    /** Creates a new ExportPprofRequest instance. */
    constructor($$source: Partial<ExportPprofRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportPprofRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportPprofRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportPprofRequest($$parsedSource as Partial<ExportPprofRequest>);
    }
}

export class ExportPprofResponse {
    "outputPath": string;
    "bytes": number;

    /** Creates a new ExportPprofResponse instance. */
    constructor($$source: Partial<ExportPprofResponse> = {}) {
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportPprofResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportPprofResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportPprofResponse($$parsedSource as Partial<ExportPprofResponse>);
    }
}

// Private type creation functions
const $$createType0 = profiler$0.DrilldownFilter.createFrom;
const $$createType1 = $Create.Array($$createType0);
