// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiler$0 from "../../internal/profiler/models.js";

/**
 * AnalyzeAsyncResponse is returned to the renderer immediately. The actual
 * AnalysisResult arrives later via the `analyze:done` event keyed by taskId.
 */
export class AnalyzeAsyncResponse {
    "taskId": string;

    /** Creates a new AnalyzeAsyncResponse instance. */
    constructor($$source: Partial<AnalyzeAsyncResponse> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeAsyncResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeAsyncResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeAsyncResponse($$parsedSource as Partial<AnalyzeAsyncResponse>);
    }
}

export class AnalyzeCancelledEvent {
    "taskId": string;

    /** Creates a new AnalyzeCancelledEvent instance. */
    constructor($$source: Partial<AnalyzeCancelledEvent> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeCancelledEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeCancelledEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeCancelledEvent($$parsedSource as Partial<AnalyzeCancelledEvent>);
    }
}

/**
 * AnalyzeDoneEvent / AnalyzeErrorEvent / AnalyzeCancelledEvent are emitted
 * over Wails Event so the renderer doesn't have to poll.
 */
export class AnalyzeDoneEvent {
    "taskId": string;
    "result": profiler$0.AnalysisResult;

    /** Creates a new AnalyzeDoneEvent instance. */
    constructor($$source: Partial<AnalyzeDoneEvent> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = (new profiler$0.AnalysisResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeDoneEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeDoneEvent {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new AnalyzeDoneEvent($$parsedSource as Partial<AnalyzeDoneEvent>);
    }
}

export class AnalyzeErrorEvent {
    "taskId": string;
    "message": string;

    /** Creates a new AnalyzeErrorEvent instance. */
    constructor($$source: Partial<AnalyzeErrorEvent> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeErrorEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeErrorEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeErrorEvent($$parsedSource as Partial<AnalyzeErrorEvent>);
    }
}

export class AnalyzeRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;

    /**
     * DebugLog opts the renderer into the portable parser debug log
     * (T-239g). When true and the parse encounters issues, a JSON file is
     * written under DebugLogDir (default: <cwd>/archscope-debug/) and its
     * path is returned in the result metadata.
     */
    "debugLog"?: boolean;
    "debugLogDir"?: string;

    /** Creates a new AnalyzeRequest instance. */
    constructor($$source: Partial<AnalyzeRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeRequest($$parsedSource as Partial<AnalyzeRequest>);
    }
}

/**
 * DebugLogResult is the response shape for ProfilerService.WriteDebugLog.
 */
export class DebugLogResult {
    "outputPath": string;
    "verdict": string;
    "verdicts"?: string;

    /** Creates a new DebugLogResult instance. */
    constructor($$source: Partial<DebugLogResult> = {}) {
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugLogResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugLogResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DebugLogResult($$parsedSource as Partial<DebugLogResult>);
    }
}

export class DiffRequest {
    "baselinePath": string;
    "targetPath": string;
    "baselineFormat": string;
    "targetFormat": string;
    "intervalMs": number;
    "topN": number;
    "normalize": boolean;

    /** Creates a new DiffRequest instance. */
    constructor($$source: Partial<DiffRequest> = {}) {
        if (!("baselinePath" in $$source)) {
            this["baselinePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }
        if (!("baselineFormat" in $$source)) {
            this["baselineFormat"] = "";
        }
        if (!("targetFormat" in $$source)) {
            this["targetFormat"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("normalize" in $$source)) {
            this["normalize"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffRequest($$parsedSource as Partial<DiffRequest>);
    }
}

export class DrilldownRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;

    /**
     * DebugLog opts the renderer into the portable parser debug log
     * (T-239g). When true and the parse encounters issues, a JSON file is
     * written under DebugLogDir (default: <cwd>/archscope-debug/) and its
     * path is returned in the result metadata.
     */
    "debugLog"?: boolean;
    "debugLogDir"?: string;
    "filters": profiler$0.DrilldownFilter[];

    /** Creates a new DrilldownRequest instance. */
    constructor($$source: Partial<DrilldownRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }
        if (!("filters" in $$source)) {
            this["filters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrilldownRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DrilldownRequest {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField9_0($$parsedSource["filters"]);
        }
        return new DrilldownRequest($$parsedSource as Partial<DrilldownRequest>);
    }
}

export class ExportPprofRequest {
    "path": string;
    "format": string;
    "intervalMs": number;
    "elapsedSec": number;
    "topN": number;
    "profileKind": string;
    "timelineBaseMethod": string;

    /**
     * DebugLog opts the renderer into the portable parser debug log
     * (T-239g). When true and the parse encounters issues, a JSON file is
     * written under DebugLogDir (default: <cwd>/archscope-debug/) and its
     * path is returned in the result metadata.
     */
    "debugLog"?: boolean;
    "debugLogDir"?: string;
    "outputPath": string;

    /** Creates a new ExportPprofRequest instance. */
    constructor($$source: Partial<ExportPprofRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("intervalMs" in $$source)) {
            this["intervalMs"] = 0;
        }
        if (!("elapsedSec" in $$source)) {
            this["elapsedSec"] = 0;
        }
        if (!("topN" in $$source)) {
            this["topN"] = 0;
        }
        if (!("profileKind" in $$source)) {
            this["profileKind"] = "";
        }
        if (!("timelineBaseMethod" in $$source)) {
            this["timelineBaseMethod"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportPprofRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportPprofRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportPprofRequest($$parsedSource as Partial<ExportPprofRequest>);
    }
}

export class ExportPprofResponse {
    "outputPath": string;
    "bytes": number;

    /** Creates a new ExportPprofResponse instance. */
    constructor($$source: Partial<ExportPprofResponse> = {}) {
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportPprofResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportPprofResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportPprofResponse($$parsedSource as Partial<ExportPprofResponse>);
    }
}

// Private type creation functions
const $$createType0 = profiler$0.AnalysisResult.createFrom;
const $$createType1 = profiler$0.DrilldownFilter.createFrom;
const $$createType2 = $Create.Array($$createType1);
