// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiler$0 from "../../internal/profiler/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Analyze(req: $models.AnalyzeRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(2962401776, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeAsync starts a non-blocking analysis. Returns a taskId immediately;
 * the renderer listens for `analyze:done` / `analyze:error` /
 * `analyze:cancelled` events keyed by that taskId. The progress log is
 * opened synchronously so its path is present in the response, giving
 * the renderer something to show even if the OS kills the process
 * before the result event arrives.
 */
export function AnalyzeAsync(req: $models.AnalyzeRequest): $CancellablePromise<$models.AnalyzeAsyncResponse> {
    return $Call.ByID(1198804148, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Cancel signals a previously started AnalyzeAsync to discard its result.
 * Returns true if the task existed; false if it had already finished.
 */
export function Cancel(taskID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2907751950, taskID);
}

export function Diff(req: $models.DiffRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(3785065275, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Drilldown(req: $models.DrilldownRequest): $CancellablePromise<profiler$0.DrilldownStage[]> {
    return $Call.ByID(1083076133, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExportPprof(req: $models.ExportPprofRequest): $CancellablePromise<$models.ExportPprofResponse> {
    return $Call.ByID(3897807737, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PickPprofOutput(): $CancellablePromise<string> {
    return $Call.ByID(667369069);
}

export function PickProfileFile(): $CancellablePromise<string> {
    return $Call.ByID(3229459112);
}

/**
 * WriteDebugLog runs an analysis with the debug log enabled and returns the
 * saved JSON path. Renderer uses this from the Diagnostics tab.
 */
export function WriteDebugLog(req: $models.AnalyzeRequest): $CancellablePromise<$models.DebugLogResult> {
    return $Call.ByID(45456632, req).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = profiler$0.AnalysisResult.createFrom;
const $$createType1 = $models.AnalyzeAsyncResponse.createFrom;
const $$createType2 = profiler$0.DrilldownStage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ExportPprofResponse.createFrom;
const $$createType5 = $models.DebugLogResult.createFrom;
