// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profiler$0 from "../../internal/profiler/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Analyze(req: $models.AnalyzeRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(2962401776, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Diff(req: $models.DiffRequest): $CancellablePromise<profiler$0.AnalysisResult> {
    return $Call.ByID(3785065275, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Drilldown(req: $models.DrilldownRequest): $CancellablePromise<profiler$0.DrilldownStage[]> {
    return $Call.ByID(1083076133, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ExportPprof(req: $models.ExportPprofRequest): $CancellablePromise<$models.ExportPprofResponse> {
    return $Call.ByID(3897807737, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function PickPprofOutput(): $CancellablePromise<string> {
    return $Call.ByID(667369069);
}

export function PickProfileFile(): $CancellablePromise<string> {
    return $Call.ByID(3229459112);
}

// Private type creation functions
const $$createType0 = profiler$0.AnalysisResult.createFrom;
const $$createType1 = profiler$0.DrilldownStage.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ExportPprofResponse.createFrom;
