// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../../time/models.js";

export class Status {
    "state": string;
    "fingerprint"?: string;
    "stores": string[];
    "expiresAt"?: time$0.Time;
    "error"?: string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("stores" in $$source)) {
            this["stores"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stores" in $$parsedSource) {
            $$parsedSource["stores"] = $$createField2_0($$parsedSource["stores"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
